/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComposerRouteImport } from './routes/_authenticated/composer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEmailsIdRouteImport } from './routes/_authenticated/emails/$id'
import { Route as ApiPublicOauthGmailCallbackRouteImport } from './routes/api/public/oauth/gmail-callback'
import { Route as ApiPublicHooksDailyEmailReportRouteImport } from './routes/api/public/hooks/daily-email-report'
import { Route as ApiPublicHooksBounceMonitorRouteImport } from './routes/api/public/hooks/bounce-monitor'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComposerRoute = AuthenticatedComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsIdRoute = AuthenticatedEmailsIdRouteImport.update({
  id: '/emails/$id',
  path: '/emails/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicOauthGmailCallbackRoute =
  ApiPublicOauthGmailCallbackRouteImport.update({
    id: '/api/public/oauth/gmail-callback',
    path: '/api/public/oauth/gmail-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyEmailReportRoute =
  ApiPublicHooksDailyEmailReportRouteImport.update({
    id: '/api/public/hooks/daily-email-report',
    path: '/api/public/hooks/daily-email-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBounceMonitorRoute =
  ApiPublicHooksBounceMonitorRouteImport.update({
    id: '/api/public/hooks/bounce-monitor',
    path: '/api/public/hooks/bounce-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/composer': typeof AuthenticatedComposerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emails/$id': typeof AuthenticatedEmailsIdRoute
  '/api/public/hooks/bounce-monitor': typeof ApiPublicHooksBounceMonitorRoute
  '/api/public/hooks/daily-email-report': typeof ApiPublicHooksDailyEmailReportRoute
  '/api/public/oauth/gmail-callback': typeof ApiPublicOauthGmailCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/composer': typeof AuthenticatedComposerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emails/$id': typeof AuthenticatedEmailsIdRoute
  '/api/public/hooks/bounce-monitor': typeof ApiPublicHooksBounceMonitorRoute
  '/api/public/hooks/daily-email-report': typeof ApiPublicHooksDailyEmailReportRoute
  '/api/public/oauth/gmail-callback': typeof ApiPublicOauthGmailCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/composer': typeof AuthenticatedComposerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emails/$id': typeof AuthenticatedEmailsIdRoute
  '/api/public/hooks/bounce-monitor': typeof ApiPublicHooksBounceMonitorRoute
  '/api/public/hooks/daily-email-report': typeof ApiPublicHooksDailyEmailReportRoute
  '/api/public/oauth/gmail-callback': typeof ApiPublicOauthGmailCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/composer'
    | '/dashboard'
    | '/emails/$id'
    | '/api/public/hooks/bounce-monitor'
    | '/api/public/hooks/daily-email-report'
    | '/api/public/oauth/gmail-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/composer'
    | '/dashboard'
    | '/emails/$id'
    | '/api/public/hooks/bounce-monitor'
    | '/api/public/hooks/daily-email-report'
    | '/api/public/oauth/gmail-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/composer'
    | '/_authenticated/dashboard'
    | '/_authenticated/emails/$id'
    | '/api/public/hooks/bounce-monitor'
    | '/api/public/hooks/daily-email-report'
    | '/api/public/oauth/gmail-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksBounceMonitorRoute: typeof ApiPublicHooksBounceMonitorRoute
  ApiPublicHooksDailyEmailReportRoute: typeof ApiPublicHooksDailyEmailReportRoute
  ApiPublicOauthGmailCallbackRoute: typeof ApiPublicOauthGmailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/composer': {
      id: '/_authenticated/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof AuthenticatedComposerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails/$id': {
      id: '/_authenticated/emails/$id'
      path: '/emails/$id'
      fullPath: '/emails/$id'
      preLoaderRoute: typeof AuthenticatedEmailsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/oauth/gmail-callback': {
      id: '/api/public/oauth/gmail-callback'
      path: '/api/public/oauth/gmail-callback'
      fullPath: '/api/public/oauth/gmail-callback'
      preLoaderRoute: typeof ApiPublicOauthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-email-report': {
      id: '/api/public/hooks/daily-email-report'
      path: '/api/public/hooks/daily-email-report'
      fullPath: '/api/public/hooks/daily-email-report'
      preLoaderRoute: typeof ApiPublicHooksDailyEmailReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bounce-monitor': {
      id: '/api/public/hooks/bounce-monitor'
      path: '/api/public/hooks/bounce-monitor'
      fullPath: '/api/public/hooks/bounce-monitor'
      preLoaderRoute: typeof ApiPublicHooksBounceMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedComposerRoute: typeof AuthenticatedComposerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailsIdRoute: typeof AuthenticatedEmailsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedComposerRoute: AuthenticatedComposerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailsIdRoute: AuthenticatedEmailsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksBounceMonitorRoute: ApiPublicHooksBounceMonitorRoute,
  ApiPublicHooksDailyEmailReportRoute: ApiPublicHooksDailyEmailReportRoute,
  ApiPublicOauthGmailCallbackRoute: ApiPublicOauthGmailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
